dist: bionic
language: c

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

os:
  - linux

install:
  - sudo apt-get install libnss3-dev libsodium-dev libssl-dev libwolfssl-dev

script:
  - cat /proc/cpuinfo
  - mkdir build && cd build
  - cmake .. && make -j $(nproc)
  - ./crypto_benchmark
