dist: bionic
language: c

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2.tar.gz && tar -xzvf cmake-3.16.2.tar.gz

install:
  - cd cmake-3.16.2 && ./bootstrap && make -j $(nproc) && sudo make install && cd ..
  - sudo apt-get install libnss3-dev libsodium-dev libssl-dev libwolfssl-dev

script:
  - cat /proc/cpuinfo
  - mkdir build && cd build
  - cmake .. && make -j $(nproc)
  - ./crypto_benchmark
